### ISSUE TITLE
Issue converting Donkey Kong Mattel to intv2

### ISSUE THREAD

**Issue by mholzinger** [dot-bob/int2intv#1]
Thanks for starting this project! Fantastic work!

I'm converting some Intellivision dumps from the GoodINTV v2.03 set. Many work with the options in the map you've shown. Yay!

The following converted file although doesn't load in the Intv2 format that the Intellivision core on the NT mini expects to load. We just get a green screen.

Resulting file: 

```
Donkey\ Kong\ \(1982\)\ \(Coleco\).intv
crc32: 83f26f05
sha1sum: 7f223bb11e4bb678be6cbf008a37a847d37b21ac
```
[converted_rom.tar.gz](https://github.com/dot-bob/int2intv/files/5700584/converted_rom.tar.gz)

Also, just for the sake of testing, I went through every single map option [0-9][99] to check the output of converting the file.

As we might expect non worked out.

Happy to provide my jzintv output from running the unconverted file on my local machine if that helps!

**Comment by dot-bob** [comment]
@mholzinger,

 The converted rom you provided is identical to the one I have on my system and it is working fine for me.  I think you are using the Intellivision II bios CRC32 A85FC6DD .  If I switch to this bios I get the green screen you mention.  The Intellivision II contained code in the bios that attempted to prevent 3rd party titles from running.  Try converting the executive bios CRC32 CBCE86F7 (Intellivision I bios) which is EEB54C63 after conversion as this what I am using.

**Comment by mholzinger** [comment]
My good friend that was IT!

I should have realized that since I own an Intellivision2 and the only change in that unit was that indeed, it prevents a few games from running.

Thanks for the awesome work.

I have the new bios, named it `execrom.bin` and placed in the /BIOS/ folder and selected as the main bios file.

I don't think we actually ever need the Intellivision II bios for anything at all.

Thanks a million!

**Comment by tjanas** [comment]
@dot-bob thank you for providing this tool and information. Do you know how I could obtain the existing INTV2 format Intellivision II BIOS (CRC32 A85FC6DD, 8728 bytes)? I suspect the source file to convert is `ro-3-9506-010.ic6` from `intv/intv2' in MAME (CRC32 DD7E1237, 8704 bytes).

**Comment by tjanas** [comment]
Never mind, I think I understand now.

For the Intellivision II BIOS 
`00 04 00 00 00 01 00 00`
(first 512 bytes of data)
`00 10 00 00 00 10 00 00`
(remaining 8192 bytes)
`00 00 00 00 00 00 00 00`

That Intellivision II exec rom has its first 512 bytes at address 0x0400 and the remaining 8k bytes at address 0x1000
