### ISSUE TITLE
Datasize in Map #1, #2 and #5 parts are maybe wrong?

### ISSUE THREAD

**Issue by Elrinth** [dot-bob/int2intv#2]
If I look in: http://spatula-city.org/~im14u2c/intv/dl/intv_maps.zip
and compare how 3.cfg is and 5.cfg is.
For 3 you coded EVEN numbers. but for 1,2 and 5 you used uneven numbers: 0x2FFF. maybe it don't matter. but i can't get the expected result.

I am getting wrong CRC32 for Commando which is originally 3289C8BA. Maybe I have bad rom? found same bad rom on two different places :/ fairly sure the tool is updating commando rom wrongly. But I'd like to hear your input!

Also here is more info (thank you tjanas): https://github.com/mamedev/mame/blob/master/hash/intv.xml

**Comment by tjanas** [comment]
From https://github.com/mamedev/mame/blob/master/hash/intv.xml:
```
    <software name="commando">
        <description>Commando</description>
        <year>1987</year>
        <publisher>INTV</publisher>
        <info name="serial" value="9000"/>
        <part name="cart" interface="intv_cart">
            <feature name="slot" value="intv_rom" />
            <dataarea name="5000" size="0x4000">
                <rom name="commando.50" size="0x4000" crc="2b6d633d" sha1="777e5a0e7033b5f80197eb069cd204e62d09eb63"/>
            </dataarea>
            <dataarea name="9000" size="0x4000">
                <rom name="commando.90" size="0x4000" crc="fc44ea3c" sha1="5a95ea2924d3b0bfc4e353d6ffc4966f4bdfcd58"/>
            </dataarea>
        </part>
    </software>
```
The [spreadsheet](https://docs.google.com/spreadsheets/d/1SE-URZLioX19FIbmX200VBaKcCyuv-NCPKt56Hf37Fk) reference lists Commando as mapper 2. The int2intv code does not seem to match the implied mapper 2 layout per the xml above (two chunks, at word offsets 0x5000 and 0x9000, both of size 0x4000 bytes, aka 0x2000 words).

**Comment by tjanas** [comment]
Also, from https://www.swissdisk.com/~bcollins/intv/intvromutil.c:
```
    { 0x3289C8BA,
      "Commando", "INTV", "1987",
      32768, 0, 0,
      { {0x5000, 0x6FFF}, {0x9000, 0xAFFF} } },
```
The above indicates there are 32768 rom bytes, with two chunks, where the first starts at word 0x5000 and ends inclusive with word 0x6FFF (if you take the difference and add one, you get size of 0x2000 words) and the last starts with word 0x9000 and ends inclusive with word 0AFFF (also a size of 0x2000 words).

The ROM for Commando that currently exists in the SMDB for the Analogue Nt Mini Noir has the following attributes:
```
00 50 00 00    00 20 00 00   <-- address 0x5000, size 0x2000 words (0x4000 bytes)
(...data...)
00 90 00 00    00 20 00 00   <-- address 0x9000, size 0x2000 words (0x4000 bytes)
(...data...)
00 00 00 00    00 00 00 00   <-- end of file trailer
```

**Comment by dot-bob** [comment]
Try the latest release.  I forgot to decrement some of the byte counters so larger roms didn't get mapped properly.

**Comment by Elrinth** [comment]
It seems you fixed it. Well done!
